name: Check Dragonholic Paid Feed

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  sanity-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with: { python-version: '3.x' }

      - name: Install Dependencies
        run: pip install feedparser aiohttp

      - name: Run “All‑Paid” Checker
        run: python check_paid_all.py
